model_name: "timesformer"
output_dir: "D:/Abdulaziz/daisee_benchmark/results/timesformer"

data:
  raw_data_root: "D:/Abdulaziz/daisee_benchmark/DAiSEE_Dataset_Raw/daisee_dataset/DAiSEE"
  data_mode: "video_only"
  use_audio: false
  num_workers: 4
  
training:
  batch_size: 2
  epochs: 47
  num_frames: 16
  learning_rate: 0.0001
  optimizer: "adamw"
  num_labels: 4